apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: demo-java-app
spec:
  selector:
    matchLabels:
      app: demo-java-apps
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: demo-java-app
    spec:
      containers:
        - name: spring-boot-k8s
          image: yedukondalu212/javaapplicationrepo:latest 
# Image that will be used to containers in the cluster
